### ISSUE TITLE
Licensing terms?

### ISSUE THREAD

**Issue by gkelly** [ryankurte/rust-radio-sx127x#9]
I love this crate, but the licensing terms don't appear to be explicit. Can you clarify what they are?

**Comment by ryankurte** [comment]
Glad to hear it / hope it has been useful! I chose [MPL-2.0](https://choosealicense.com/licenses/mpl-2.0/) which is specified in [cargo.toml](https://github.com/ryankurte/rust-radio-sx127x/blob/master/Cargo.toml#L7), and have added a `LICENSE.txt` to the repo now.

**Comment by gkelly** [comment]
Thanks so much!
